/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2016-12-20 10:25:33:0253
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char BSP_GNSS_POWER_PIN = 10;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_EINT = 1;
const char BSP_GNSS_POWER_PIN_M_AUXADCIN_4 = 2;
const char BSP_GNSS_POWER_PIN_M_DEBUGMON15 = 8;
const char BSP_GNSS_POWER_PIN_M_BTPRI = 9;


const char BSP_BIO_SENSOR_RST_PORT_PIN = 11;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_GPIO = 0;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_EINT = 1;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_BT_BUCK_EN_HW = 2;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_MA_EDIDO = 3;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_MA_SPI1_B_CS = 4;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_PWM0 = 5;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_SLA_EDIDO = 6;


const char BSP_BIO_SENSOR_32K = 14;
const char BSP_BIO_SENSOR_32K_M_GPIO = 0;
const char BSP_BIO_SENSOR_32K_M_EINT = 1;
const char BSP_BIO_SENSOR_32K_M_CLKO = 2;
const char BSP_BIO_SENSOR_32K_M_MA_EDICK = 3;
const char BSP_BIO_SENSOR_32K_M_MA_SPI1_B_MISO = 4;
const char BSP_BIO_SENSOR_32K_M_PWM3 = 5;
const char BSP_BIO_SENSOR_32K_M_SLA_EDICK = 6;


const char BSP_CTP_EINT_PIN = 15;
const char BSP_CTP_EINT_PIN_M_GPIO = 0;
const char BSP_CTP_EINT_PIN_M_EINT = 1;
const char BSP_CTP_EINT_PIN_M_PWM4 = 5;


const char BSP_BIO_SENSOR_AFE_PWD_PIN = 29;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_GPIO = 0;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_CMCSK = 1;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_LPTE = 2;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_CMCSD2 = 4;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_EINT = 5;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_DEBUGMON15 = 7;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_MC1_B_DA1 = 8;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_BT_RGPIO2 = 9;


const char BSP_CTP_SCL_PIN = 30;
const char BSP_CTP_SCL_PIN_M_GPIO = 0;
const char BSP_CTP_SCL_PIN_M_SCL0 = 1;
const char BSP_CTP_SCL_PIN_M_EINT = 2;
const char BSP_CTP_SCL_PIN_M_PWM0 = 3;
const char BSP_CTP_SCL_PIN_M_U1RXD = 4;
const char BSP_CTP_SCL_PIN_M_MC0_CK = 5;
const char BSP_CTP_SCL_PIN_M_BT_RGPIO0 = 6;
const char BSP_CTP_SCL_PIN_M_DEBUGMON0 = 7;
const char BSP_CTP_SCL_PIN_M_SCL2 = 9;


const char BSP_CTP_SDA_PIN = 31;
const char BSP_CTP_SDA_PIN_M_GPIO = 0;
const char BSP_CTP_SDA_PIN_M_SDA0 = 1;
const char BSP_CTP_SDA_PIN_M_EINT = 2;
const char BSP_CTP_SDA_PIN_M_PWM1 = 3;
const char BSP_CTP_SDA_PIN_M_U1TXD = 4;
const char BSP_CTP_SDA_PIN_M_MC0_CM0 = 5;
const char BSP_CTP_SDA_PIN_M_DEBUGMIN1 = 6;
const char BSP_CTP_SDA_PIN_M_DEBUGMON1 = 7;
const char BSP_CTP_SDA_PIN_M_BT_RGPIO1 = 8;
const char BSP_CTP_SDA_PIN_M_SDA2 = 9;


const char SENSOR_EINT_PIN = 33;
const char SENSOR_EINT_PIN_M_GPIO = 0;
const char SENSOR_EINT_PIN_M_SLV_SPI0_SCK = 1;
const char SENSOR_EINT_PIN_M_EINT = 2;
const char SENSOR_EINT_PIN_M_PWM3 = 3;
const char SENSOR_EINT_PIN_M_DAIPCMIN = 4;
const char SENSOR_EINT_PIN_M_MC0_DA1 = 5;
const char SENSOR_EINT_PIN_M_BT_RGPIO3 = 6;
const char SENSOR_EINT_PIN_M_DEBUGMON3 = 7;
const char SENSOR_EINT_PIN_M_MA_SPI3_B_SCK = 9;


const char SENSOR_EINT_G_PIN = 34;
const char SENSOR_EINT_G_PIN_M_GPIO = 0;
const char SENSOR_EINT_G_PIN_M_SLV_SPI0_MOSI = 1;
const char SENSOR_EINT_G_PIN_M_EINT = 2;
const char SENSOR_EINT_G_PIN_M_PWM4 = 3;
const char SENSOR_EINT_G_PIN_M_DAICLK = 4;
const char SENSOR_EINT_G_PIN_M_MC0_DA2 = 5;
const char SENSOR_EINT_G_PIN_M_BT_RGPIO4 = 6;
const char SENSOR_EINT_G_PIN_M_DEBUGMON4 = 7;
const char SENSOR_EINT_G_PIN_M_MA_SPI3_B_MOSI = 9;


const char BSP_BIO_SENSOR_PPG_VDRV_EN = 35;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_GPIO = 0;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_SLV_SPI0_MISO = 1;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_EINT = 2;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_PWM5 = 3;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_DAIPCMOUT = 4;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_MC0_DA3 = 5;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_CLKO = 6;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_BT_RGPIO5 = 7;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_MA_SPI3_B_MISO = 9;


const char BSP_CTP_RST_PIN = 47;
const char BSP_CTP_RST_PIN_M_GPIO = 0;
const char BSP_CTP_RST_PIN_M_MA_SPI1_CS1 = 1;
const char BSP_CTP_RST_PIN_M_DEBUGMON2 = 7;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_COL0_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;





