/*
 * Generated by MTK Easy PinMux Tool Version 2.1.0 for 5932. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-20 15:57:37:0919
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char HAL_SDIO_SLV_CK_PIN = 11;
const char HAL_SDIO_SLV_CK_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_CK_PIN_M_EINT = 1;
const char HAL_SDIO_SLV_CK_PIN_M_PWM3 = 2;
const char HAL_SDIO_SLV_CK_PIN_M_URXD2 = 3;
const char HAL_SDIO_SLV_CK_PIN_M_MA_MC0_CK = 4;
const char HAL_SDIO_SLV_CK_PIN_M_SLV_MC0_CK = 5;
const char HAL_SDIO_SLV_CK_PIN_M_CLKO = 6;
const char HAL_SDIO_SLV_CK_PIN_M_DEBUGMON8 = 7;
const char HAL_SDIO_SLV_CK_PIN_M_WF_AICE_TCKC = 8;
const char HAL_SDIO_SLV_CK_PIN_M_WIFI_ANT_SEL0 = 9;
const char HAL_SDIO_SLV_CK_PIN_M_I2S_RX = 10;


const char HAL_SDIO_SLV_CM_PIN = 12;
const char HAL_SDIO_SLV_CM_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_CM_PIN_M_SPISLV_B_SIO3 = 1;
const char HAL_SDIO_SLV_CM_PIN_M_SPIMST_B_SIO3 = 2;
const char HAL_SDIO_SLV_CM_PIN_M_UTXD2 = 3;
const char HAL_SDIO_SLV_CM_PIN_M_MA_MC0_CM0 = 4;
const char HAL_SDIO_SLV_CM_PIN_M_SLV_MC0_CM0 = 5;
const char HAL_SDIO_SLV_CM_PIN_M_EINT = 6;
const char HAL_SDIO_SLV_CM_PIN_M_DEBUGMON9 = 7;
const char HAL_SDIO_SLV_CM_PIN_M_WF_AICE_TMSC = 8;
const char HAL_SDIO_SLV_CM_PIN_M_WIFI_ANT_SEL1 = 9;
const char HAL_SDIO_SLV_CM_PIN_M_I2S_TX = 10;


const char HAL_SDIO_SLV_DA0_PIN = 13;
const char HAL_SDIO_SLV_DA0_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_DA0_PIN_M_SPISLV_B_SIO2 = 1;
const char HAL_SDIO_SLV_DA0_PIN_M_SPIMST_B_SIO2 = 2;
const char HAL_SDIO_SLV_DA0_PIN_M_U2RTS = 3;
const char HAL_SDIO_SLV_DA0_PIN_M_MA_MC0_DA0 = 4;
const char HAL_SDIO_SLV_DA0_PIN_M_SLV_MC0_DA0 = 5;
const char HAL_SDIO_SLV_DA0_PIN_M_CLKO = 6;
const char HAL_SDIO_SLV_DA0_PIN_M_DEBUGMON10 = 7;
const char HAL_SDIO_SLV_DA0_PIN_M_EINT = 8;
const char HAL_SDIO_SLV_DA0_PIN_M_WF_JTDI = 9;
const char HAL_SDIO_SLV_DA0_PIN_M_I2S_WS = 10;


const char HAL_SDIO_SLV_DA1_PIN = 14;
const char HAL_SDIO_SLV_DA1_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_DA1_PIN_M_SPISLV_B_SIO1 = 1;
const char HAL_SDIO_SLV_DA1_PIN_M_SPIMST_B_SIO1 = 2;
const char HAL_SDIO_SLV_DA1_PIN_M_TDM_RX = 3;
const char HAL_SDIO_SLV_DA1_PIN_M_MA_MC0_DA1 = 4;
const char HAL_SDIO_SLV_DA1_PIN_M_SLV_MC0_DA1 = 5;
const char HAL_SDIO_SLV_DA1_PIN_M_PWM4 = 6;
const char HAL_SDIO_SLV_DA1_PIN_M_DEBUGMON11 = 7;
const char HAL_SDIO_SLV_DA1_PIN_M_EINT = 8;
const char HAL_SDIO_SLV_DA1_PIN_M_WF_JTMS = 9;
const char HAL_SDIO_SLV_DA1_PIN_M_CLKO = 10;


const char HAL_SDIO_SLV_DA2_PIN = 15;
const char HAL_SDIO_SLV_DA2_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_DA2_PIN_M_SPISLV_B_SIO0 = 1;
const char HAL_SDIO_SLV_DA2_PIN_M_SPIMST_B_SIO0 = 2;
const char HAL_SDIO_SLV_DA2_PIN_M_TDM_TX = 3;
const char HAL_SDIO_SLV_DA2_PIN_M_MA_MC0_DA2 = 4;
const char HAL_SDIO_SLV_DA2_PIN_M_SLV_MC0_DA2 = 5;
const char HAL_SDIO_SLV_DA2_PIN_M_SCL1 = 6;
const char HAL_SDIO_SLV_DA2_PIN_M_DEBUGMON12 = 7;
const char HAL_SDIO_SLV_DA2_PIN_M_EINT = 8;
const char HAL_SDIO_SLV_DA2_PIN_M_WF_JTCK = 9;
const char HAL_SDIO_SLV_DA2_PIN_M_PWM3 = 10;


const char HAL_SDIO_SLV_DA3_PIN = 16;
const char HAL_SDIO_SLV_DA3_PIN_M_GPIO = 0;
const char HAL_SDIO_SLV_DA3_PIN_M_SPISLV_B_SCK = 1;
const char HAL_SDIO_SLV_DA3_PIN_M_SPIMST_B_SCK = 2;
const char HAL_SDIO_SLV_DA3_PIN_M_TDM_WS = 3;
const char HAL_SDIO_SLV_DA3_PIN_M_MA_MC0_DA3 = 4;
const char HAL_SDIO_SLV_DA3_PIN_M_SLV_MC0_DA3 = 5;
const char HAL_SDIO_SLV_DA3_PIN_M_SDA1 = 6;
const char HAL_SDIO_SLV_DA3_PIN_M_DEBUGMON13 = 7;
const char HAL_SDIO_SLV_DA3_PIN_M_EINT = 8;
const char HAL_SDIO_SLV_DA3_PIN_M_WF_JTRST_B = 9;
const char HAL_SDIO_SLV_DA3_PIN_M_N9_UTXD3 = 10;


const char HAL_UART0_RXD_PIN = 19;
const char HAL_UART0_RXD_PIN_M_GPIO = 0;
const char HAL_UART0_RXD_PIN_M_URXD0 = 1;
const char HAL_UART0_RXD_PIN_M_EINT = 2;
const char HAL_UART0_RXD_PIN_M_SCL1 = 3;
const char HAL_UART0_RXD_PIN_M_PWM5 = 5;
const char HAL_UART0_RXD_PIN_M_AUXADC2 = 6;
const char HAL_UART0_RXD_PIN_M_WIFI_EXT_CLK = 7;


const char HAL_UART0_TXD_PIN = 20;
const char HAL_UART0_TXD_PIN_M_GPIO = 0;
const char HAL_UART0_TXD_PIN_M_UTXD0 = 1;
const char HAL_UART0_TXD_PIN_M_EINT = 2;
const char HAL_UART0_TXD_PIN_M_AUXADC3 = 6;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char EXT_NTC_POWER_SW_PIN = 0xff;
const char EXT_NTC_ADC_PIN = 0xff;
const char EXT_DSP_POWER_SW_PIN = 0xff;
const char EXT_DSP_CLK_SW_PIN = 0xff;
const char EXT_DSP_RTC_CLK_SW_PIN = 0xff;
const char EXT_DSP_32K_CLK_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;





