IC_CONFIG                             = mt2523
BOARD_CONFIG                          = mt2523_hdk

# combo sensor of accelerometer and gyroscope
#MTK_SENSOR_ACCELEROMETER_USE = BMI160
#MTK_SENSOR_MAGNETIC_USE = YAS533
#MTK_SENSOR_BAROMETER_USE = BMP280
#MTK_SENSOR_PROXIMITY_USE = CM36672
MTK_SENSOR_BIO_USE = MT2511
MTK_SENSOR_ACCELEROMETER_USE = BMA255
MTK_SENSOR_BIO_MODULE = EVERLIGHT
HR_PPG_128HZ = y

# USB
MTK_USB_DEMO_ENABLED = y

# fusion algorithm
#FUSION_PEDOMETER_USE = M_INHOUSE_PEDOMETER
#FUSION_SLEEP_TRACKER_USE = M_INHOUSE_SLEEP_TRACKER
#FUSION_HEART_RATE_MONITOR_USE = M_INHOUSE_HEART_RATE_MONITOR
#FUSION_HEART_RATE_VARIABILITY_USE = M_INHOUSE_HEART_RATE_VARIABILITY
#FUSION_BLOOD_PRESSURE_USE = M_INHOUSE_BLOOD_PRESSURE

#CFLAGS += -DHEART_RATE_MONITOR_OUT_PATTERN
#CFLAGS += -DHEART_RATE_VARIABILITY_OUT_PATTERN
#CFLAGS += -DBLOOD_PRESSURE_OUT_PATTERN
CFLAGS += -DSENSOR_MANAGER_LOG_DISABLE
CFLAGS += -DFUSION_REPORT_RAW_DATA_ENABLE

# port service
MTK_PORT_SERVICE_ENABLE = y

# atci via port service
MTK_ATCI_VIA_PORT_SERVICE = y

MTK_NVDM_ENABLE           = y

PLATFORM_DEVICE = BAND
GT_PROJECT_ENABLE = y
GT_PROJ_NAME = W269
GT_AT_GPIO_SUPPORT = y
CFLAGS += -DGT_W269_COMMON_FEATURE
__BT_ENABLE_BA__ = y

MT2511_E1 = y
MT2511_INTERFACE = SPI
MTK_SMART_BATTERY_ENABLE = y
BMA255_ORIENTATION = OPT1

ifeq ($(GT_PROJECT_ENABLE),y)
# fusion algorithm
FUSION_PEDOMETER_USE = M_INHOUSE_PEDOMETER
FUSION_SLEEP_TRACKER_USE = M_INHOUSE_SLEEP_TRACKER
FUSION_HEART_RATE_MONITOR_USE = M_INHOUSE_HEART_RATE_MONITOR
FUSION_HEART_RATE_VARIABILITY_USE = M_INHOUSE_HEART_RATE_VARIABILITY
FUSION_BLOOD_PRESSURE_USE = M_INHOUSE_BLOOD_PRESSURE
endif