ifeq ($(PROJ_PATH),)
include feature.mk
else
include $(PROJ_PATH)/feature.mk
endif

PLATFORM_DEVICE = BAND
GT_PROJECT_ENABLE = n 
GT_PROJ_NAME = W269
GT_AT_GPIO_SUPPORT = y
CFLAGS += -DGT_W269_COMMON_FEATURE



MTK_SMART_BATTERY_ENABLE = y


#CFLAGS += -DHEART_RATE_MONITOR_OUT_PATTERN 


# fusion algorithm
#FUSION_PEDOMETER_USE = M_INHOUSE_PEDOMETER
#FUSION_SLEEP_TRACKER_USE = M_INHOUSE_SLEEP_TRACKER
#FUSION_HEART_RATE_MONITOR_USE = M_INHOUSE_HEART_RATE_MONITOR
#FUSION_HEART_RATE_VARIABILITY_USE = M_INHOUSE_HEART_RATE_VARIABILITY
FUSION_BLOOD_PRESSURE_USE = M_INHOUSE_BLOOD_PRESSURE
