/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-13 09:55:10:0555
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
