/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2533. Copyright MediaTek Inc. (C) 2015.
 * 2016-12-02 16:52:22:0907
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char EXT_NTC_ADC_PIN = 0;
const char EXT_NTC_ADC_PIN_M_GPIO = 0;
const char EXT_NTC_ADC_PIN_M_EINT = 1;
const char EXT_NTC_ADC_PIN_M_AUXADCIN_0 = 2;
const char EXT_NTC_ADC_PIN_M_U2RXD = 3;
const char EXT_NTC_ADC_PIN_M_PWM0 = 4;
const char EXT_NTC_ADC_PIN_M_MA_SPI1_A_CS = 5;
const char EXT_NTC_ADC_PIN_M_MA_EDIDO = 6;
const char EXT_NTC_ADC_PIN_M_MA_SPI0_A_CS = 7;
const char EXT_NTC_ADC_PIN_M_DEBUGMON11 = 8;
const char EXT_NTC_ADC_PIN_M_BTJTDO = 9;


const char BSP_HP_ANA_SW_PIN = 3;
const char BSP_HP_ANA_SW_PIN_M_GPIO = 0;
const char BSP_HP_ANA_SW_PIN_M_EINT = 1;
const char BSP_HP_ANA_SW_PIN_M_AUXADCIN_3 = 2;
const char BSP_HP_ANA_SW_PIN_M_U3TXD = 3;
const char BSP_HP_ANA_SW_PIN_M_U0RTS = 4;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI1_A_MISO = 5;
const char BSP_HP_ANA_SW_PIN_M_MA_EDICK = 6;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI0_A_MISO = 7;
const char BSP_HP_ANA_SW_PIN_M_DEBUGMON14 = 8;
const char BSP_HP_ANA_SW_PIN_M_BTPRI = 9;


const char HAL_I2S_MASTER_EDIDO_PIN = 11;
const char HAL_I2S_MASTER_EDIDO_PIN_M_GPIO = 0;
const char HAL_I2S_MASTER_EDIDO_PIN_M_EINT = 1;
const char HAL_I2S_MASTER_EDIDO_PIN_M_BT_BUCK_EN_HW = 2;
const char HAL_I2S_MASTER_EDIDO_PIN_M_MA_EDIDO = 3;
const char HAL_I2S_MASTER_EDIDO_PIN_M_MA_SPI1_B_CS = 4;
const char HAL_I2S_MASTER_EDIDO_PIN_M_PWM0 = 5;
const char HAL_I2S_MASTER_EDIDO_PIN_M_SLA_EDIDO = 6;


const char HAL_I2S_MASTER_EDIDI_PIN = 12;
const char HAL_I2S_MASTER_EDIDI_PIN_M_GPIO = 0;
const char HAL_I2S_MASTER_EDIDI_PIN_M_EINT = 1;
const char HAL_I2S_MASTER_EDIDI_PIN_M_MA_EDIDI = 3;
const char HAL_I2S_MASTER_EDIDI_PIN_M_MA_SPI1_B_SCK = 4;
const char HAL_I2S_MASTER_EDIDI_PIN_M_PWM1 = 5;
const char HAL_I2S_MASTER_EDIDI_PIN_M_SLA_EDIDI = 6;


const char HAL_I2S_MASTER_EDIWS_PIN = 13;
const char HAL_I2S_MASTER_EDIWS_PIN_M_GPIO = 0;
const char HAL_I2S_MASTER_EDIWS_PIN_M_EINT = 1;
const char HAL_I2S_MASTER_EDIWS_PIN_M_CLKO = 2;
const char HAL_I2S_MASTER_EDIWS_PIN_M_MA_EDIWS = 3;
const char HAL_I2S_MASTER_EDIWS_PIN_M_MA_SPI1_B_MOSI = 4;
const char HAL_I2S_MASTER_EDIWS_PIN_M_PWM2 = 5;
const char HAL_I2S_MASTER_EDIWS_PIN_M_SLA_EDIWS = 6;


const char HAL_I2S_MASTER_EDICK_PIN = 14;
const char HAL_I2S_MASTER_EDICK_PIN_M_GPIO = 0;
const char HAL_I2S_MASTER_EDICK_PIN_M_EINT = 1;
const char HAL_I2S_MASTER_EDICK_PIN_M_CLKO = 2;
const char HAL_I2S_MASTER_EDICK_PIN_M_MA_EDICK = 3;
const char HAL_I2S_MASTER_EDICK_PIN_M_MA_SPI1_B_MISO = 4;
const char HAL_I2S_MASTER_EDICK_PIN_M_PWM3 = 5;
const char HAL_I2S_MASTER_EDICK_PIN_M_SLA_EDICK = 6;


const char EXT_NTC_POWER_SW_PIN = 19;
const char EXT_NTC_POWER_SW_PIN_M_GPIO = 0;
const char EXT_NTC_POWER_SW_PIN_M_KCOL1 = 1;
const char EXT_NTC_POWER_SW_PIN_M_EINT = 2;
const char EXT_NTC_POWER_SW_PIN_M_U0RTS = 3;
const char EXT_NTC_POWER_SW_PIN_M_SCL2 = 4;
const char EXT_NTC_POWER_SW_PIN_M_TRACEDATA1 = 5;
const char EXT_NTC_POWER_SW_PIN_M_DEBUGMON2 = 7;
const char EXT_NTC_POWER_SW_PIN_M_JTMS = 8;
const char EXT_NTC_POWER_SW_PIN_M_BTJTMS = 9;


const char EXT_DSP_POWER_SW_PIN = 22;
const char EXT_DSP_POWER_SW_PIN_M_GPIO = 0;
const char EXT_DSP_POWER_SW_PIN_M_KROW1 = 1;
const char EXT_DSP_POWER_SW_PIN_M_U1TXD = 2;
const char EXT_DSP_POWER_SW_PIN_M_U3TXD = 3;
const char EXT_DSP_POWER_SW_PIN_M_TRACEDATA2 = 5;
const char EXT_DSP_POWER_SW_PIN_M_TRACE_SWV = 6;
const char EXT_DSP_POWER_SW_PIN_M_DEBUGMON5 = 7;
const char EXT_DSP_POWER_SW_PIN_M_JTDO = 8;
const char EXT_DSP_POWER_SW_PIN_M_BTDBGIN = 9;


const char EXT_DSP_32K_CLK_PIN = 23;
const char EXT_DSP_32K_CLK_PIN_M_GPIO = 0;
const char EXT_DSP_32K_CLK_PIN_M_KROW0 = 1;
const char EXT_DSP_32K_CLK_PIN_M_EINT = 2;
const char EXT_DSP_32K_CLK_PIN_M_CLKO = 3;
const char EXT_DSP_32K_CLK_PIN_M_U1CTS = 4;
const char EXT_DSP_32K_CLK_PIN_M_TRACEDATA3 = 5;
const char EXT_DSP_32K_CLK_PIN_M_MC_RST = 6;
const char EXT_DSP_32K_CLK_PIN_M_DEBUGMON9 = 7;
const char EXT_DSP_32K_CLK_PIN_M_JTRST_B = 8;
const char EXT_DSP_32K_CLK_PIN_M_BTJTRSTB = 9;


const char BSP_WIFI_32K_PIN = 24;
const char BSP_WIFI_32K_PIN_M_GPIO = 0;
const char BSP_WIFI_32K_PIN_M_CMRST = 1;
const char BSP_WIFI_32K_PIN_M_LSRSTB = 2;
const char BSP_WIFI_32K_PIN_M_CLKO = 3;
const char BSP_WIFI_32K_PIN_M_EINT = 4;
const char BSP_WIFI_32K_PIN_M_GPCOUNTER_0 = 5;
const char BSP_WIFI_32K_PIN_M_JTDI = 6;
const char BSP_WIFI_32K_PIN_M_DEBUGMON10 = 7;
const char BSP_WIFI_32K_PIN_M_MC1_B_DA3 = 8;


const char BSP_WIFI_ENABLE_PIN = 25;
const char BSP_WIFI_ENABLE_PIN_M_GPIO = 0;
const char BSP_WIFI_ENABLE_PIN_M_CMPDN = 1;
const char BSP_WIFI_ENABLE_PIN_M_LSCK1 = 2;
const char BSP_WIFI_ENABLE_PIN_M_DAICLK = 3;
const char BSP_WIFI_ENABLE_PIN_M_MA_SPI2_A_CS = 4;
const char BSP_WIFI_ENABLE_PIN_M_MA_SPI3_A_CS = 5;
const char BSP_WIFI_ENABLE_PIN_M_JTMS = 6;
const char BSP_WIFI_ENABLE_PIN_M_DEBUGMON11 = 7;
const char BSP_WIFI_ENABLE_PIN_M_MC1_B_DA2 = 8;
const char BSP_WIFI_ENABLE_PIN_M_SLV_SPI0_CS = 9;


const char BSP_GNSS_POWER_PIN = 26;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_CMCSD0 = 1;
const char BSP_GNSS_POWER_PIN_M_LSCE_B1 = 2;
const char BSP_GNSS_POWER_PIN_M_DAIPCMIN = 3;
const char BSP_GNSS_POWER_PIN_M_MA_SPI2_A_SCK = 4;
const char BSP_GNSS_POWER_PIN_M_MA_SPI3_A_SCK = 5;
const char BSP_GNSS_POWER_PIN_M_JTCK = 6;
const char BSP_GNSS_POWER_PIN_M_DEBUGMON12 = 7;
const char BSP_GNSS_POWER_PIN_M_MC1_B_CM0 = 8;
const char BSP_GNSS_POWER_PIN_M_SLV_SPI0_SCK = 9;


const char BSP_WIFI_RESET_PIN = 27;
const char BSP_WIFI_RESET_PIN_M_GPIO = 0;
const char BSP_WIFI_RESET_PIN_M_CMCSD1 = 1;
const char BSP_WIFI_RESET_PIN_M_LSDA1 = 2;
const char BSP_WIFI_RESET_PIN_M_DAIPCMOUT = 3;
const char BSP_WIFI_RESET_PIN_M_MA_SPI2_A_MOSI = 4;
const char BSP_WIFI_RESET_PIN_M_MA_SPI3_A_MOSI = 5;
const char BSP_WIFI_RESET_PIN_M_JTRST_B = 6;
const char BSP_WIFI_RESET_PIN_M_DEBUGMON13 = 7;
const char BSP_WIFI_RESET_PIN_M_MC1_B_CK = 8;
const char BSP_WIFI_RESET_PIN_M_SLV_SPI0_MOSI = 9;


const char BSP_CTP_EINT_PIN = 29;
const char BSP_CTP_EINT_PIN_M_GPIO = 0;
const char BSP_CTP_EINT_PIN_M_CMCSK = 1;
const char BSP_CTP_EINT_PIN_M_LPTE = 2;
const char BSP_CTP_EINT_PIN_M_CMCSD2 = 4;
const char BSP_CTP_EINT_PIN_M_EINT = 5;
const char BSP_CTP_EINT_PIN_M_DEBUGMON15 = 7;
const char BSP_CTP_EINT_PIN_M_MC1_B_DA1 = 8;
const char BSP_CTP_EINT_PIN_M_BT_RGPIO2 = 9;


const char HAL_I2C_MASTER_0_SCL_PIN = 30;
const char HAL_I2C_MASTER_0_SCL_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_0_SCL_PIN_M_SCL0 = 1;
const char HAL_I2C_MASTER_0_SCL_PIN_M_EINT = 2;
const char HAL_I2C_MASTER_0_SCL_PIN_M_PWM0 = 3;
const char HAL_I2C_MASTER_0_SCL_PIN_M_U1RXD = 4;
const char HAL_I2C_MASTER_0_SCL_PIN_M_MC0_CK = 5;
const char HAL_I2C_MASTER_0_SCL_PIN_M_BT_RGPIO0 = 6;
const char HAL_I2C_MASTER_0_SCL_PIN_M_DEBUGMON0 = 7;
const char HAL_I2C_MASTER_0_SCL_PIN_M_SCL2 = 9;


const char HAL_I2C_MASTER_0_SDA_PIN = 31;
const char HAL_I2C_MASTER_0_SDA_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_0_SDA_PIN_M_SDA0 = 1;
const char HAL_I2C_MASTER_0_SDA_PIN_M_EINT = 2;
const char HAL_I2C_MASTER_0_SDA_PIN_M_PWM1 = 3;
const char HAL_I2C_MASTER_0_SDA_PIN_M_U1TXD = 4;
const char HAL_I2C_MASTER_0_SDA_PIN_M_MC0_CM0 = 5;
const char HAL_I2C_MASTER_0_SDA_PIN_M_DEBUGMIN1 = 6;
const char HAL_I2C_MASTER_0_SDA_PIN_M_DEBUGMON1 = 7;
const char HAL_I2C_MASTER_0_SDA_PIN_M_BT_RGPIO1 = 8;
const char HAL_I2C_MASTER_0_SDA_PIN_M_SDA2 = 9;


const char HAL_SPI_MASTER_3_CS_PIN = 32;
const char HAL_SPI_MASTER_3_CS_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER_3_CS_PIN_M_SLV_SPI0_CS = 1;
const char HAL_SPI_MASTER_3_CS_PIN_M_EINT = 2;
const char HAL_SPI_MASTER_3_CS_PIN_M_PWM2 = 3;
const char HAL_SPI_MASTER_3_CS_PIN_M_DAISYNC = 4;
const char HAL_SPI_MASTER_3_CS_PIN_M_MC0_DA0 = 5;
const char HAL_SPI_MASTER_3_CS_PIN_M_DEBUGMIN2 = 6;
const char HAL_SPI_MASTER_3_CS_PIN_M_DEBUGMON2 = 7;
const char HAL_SPI_MASTER_3_CS_PIN_M_MA_SPI3_B_CS = 9;


const char HAL_SPI_MASTER_3_SCK_PIN = 33;
const char HAL_SPI_MASTER_3_SCK_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER_3_SCK_PIN_M_SLV_SPI0_SCK = 1;
const char HAL_SPI_MASTER_3_SCK_PIN_M_EINT = 2;
const char HAL_SPI_MASTER_3_SCK_PIN_M_PWM3 = 3;
const char HAL_SPI_MASTER_3_SCK_PIN_M_DAIPCMIN = 4;
const char HAL_SPI_MASTER_3_SCK_PIN_M_MC0_DA1 = 5;
const char HAL_SPI_MASTER_3_SCK_PIN_M_BT_RGPIO3 = 6;
const char HAL_SPI_MASTER_3_SCK_PIN_M_DEBUGMON3 = 7;
const char HAL_SPI_MASTER_3_SCK_PIN_M_MA_SPI3_B_SCK = 9;


const char HAL_SPI_MASTER_3_MOSI_PIN = 34;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_SLV_SPI0_MOSI = 1;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_EINT = 2;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_PWM4 = 3;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_DAICLK = 4;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_MC0_DA2 = 5;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_BT_RGPIO4 = 6;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_DEBUGMON4 = 7;
const char HAL_SPI_MASTER_3_MOSI_PIN_M_MA_SPI3_B_MOSI = 9;


const char HAL_SPI_MASTER_3_MISO_PIN = 35;
const char HAL_SPI_MASTER_3_MISO_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER_3_MISO_PIN_M_SLV_SPI0_MISO = 1;
const char HAL_SPI_MASTER_3_MISO_PIN_M_EINT = 2;
const char HAL_SPI_MASTER_3_MISO_PIN_M_PWM5 = 3;
const char HAL_SPI_MASTER_3_MISO_PIN_M_DAIPCMOUT = 4;
const char HAL_SPI_MASTER_3_MISO_PIN_M_MC0_DA3 = 5;
const char HAL_SPI_MASTER_3_MISO_PIN_M_CLKO = 6;
const char HAL_SPI_MASTER_3_MISO_PIN_M_BT_RGPIO5 = 7;
const char HAL_SPI_MASTER_3_MISO_PIN_M_MA_SPI3_B_MISO = 9;


const char BSP_CTP_SW_I2C_SCL_PIN = 36;
const char BSP_CTP_SW_I2C_SCL_PIN_M_GPIO = 0;
const char BSP_CTP_SW_I2C_SCL_PIN_M_SCL0 = 1;
const char BSP_CTP_SW_I2C_SCL_PIN_M_SCL1 = 2;
const char BSP_CTP_SW_I2C_SCL_PIN_M_DEBUGMIN3 = 6;
const char BSP_CTP_SW_I2C_SCL_PIN_M_DEBUGMON3 = 7;


const char BSP_CTP_SW_I2C_SDA_PIN = 37;
const char BSP_CTP_SW_I2C_SDA_PIN_M_GPIO = 0;
const char BSP_CTP_SW_I2C_SDA_PIN_M_SDA0 = 1;
const char BSP_CTP_SW_I2C_SDA_PIN_M_SDA1 = 2;
const char BSP_CTP_SW_I2C_SDA_PIN_M_DEBUGMIN4 = 6;
const char BSP_CTP_SW_I2C_SDA_PIN_M_DEBUGMON4 = 7;


const char EXT_DSP_CLK_SW_PIN = 46;
const char EXT_DSP_CLK_SW_PIN_M_GPIO = 0;
const char EXT_DSP_CLK_SW_PIN_M_MA_SPI0_CS1 = 1;
const char EXT_DSP_CLK_SW_PIN_M_DEBUGMON1 = 7;


const char BSP_CTP_RST_PIN = 47;
const char BSP_CTP_RST_PIN_M_GPIO = 0;
const char BSP_CTP_RST_PIN_M_MA_SPI1_CS1 = 1;
const char BSP_CTP_RST_PIN_M_DEBUGMON2 = 7;


const char EXT_DSP_RTC_CLK_SW_PIN = 48;
const char EXT_DSP_RTC_CLK_SW_PIN_M_GPIO = 0;
const char EXT_DSP_RTC_CLK_SW_PIN_M_MA_SPI3_CS1 = 1;
const char EXT_DSP_RTC_CLK_SW_PIN_M_DEBUGMON5 = 7;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_I2C_MASTER_1_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_1_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_2_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_2_SDA_PIN = 0xff;
const char HAL_AUXADC_0_PIN = 0xff;
const char HAL_AUXADC_1_PIN = 0xff;
const char HAL_AUXADC_2_PIN = 0xff;
const char HAL_AUXADC_3_PIN = 0xff;
const char HAL_AUXADC_4_PIN = 0xff;
const char HAL_MSDC_0_CK_PIN = 0xff;
const char HAL_MSDC_0_CM_PIN = 0xff;
const char HAL_MSDC_0_DA0_PIN = 0xff;
const char HAL_MSDC_0_DA1_PIN = 0xff;
const char HAL_MSDC_0_DA2_PIN = 0xff;
const char HAL_MSDC_0_DA3_PIN = 0xff;
const char HAL_MSDC_1_CK_PIN = 0xff;
const char HAL_MSDC_1_CM_PIN = 0xff;
const char HAL_MSDC_1_DA0_PIN = 0xff;
const char HAL_MSDC_1_DA1_PIN = 0xff;
const char HAL_MSDC_1_DA2_PIN = 0xff;
const char HAL_MSDC_1_DA3_PIN = 0xff;
const char HAL_PWM_0_PIN = 0xff;
const char HAL_PWM_1_PIN = 0xff;
const char HAL_PWM_2_PIN = 0xff;
const char HAL_PWM_3_PIN = 0xff;
const char HAL_PWM_4_PIN = 0xff;
const char HAL_PWM_5_PIN = 0xff;
const char HAL_UART0_TXD_PIN = 0xff;
const char HAL_UART0_RXD_PIN = 0xff;
const char HAL_UART0_CTS_PIN = 0xff;
const char HAL_UART0_RTS_PIN = 0xff;
const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_TXD_PIN = 0xff;
const char HAL_UART1_RXD_PIN = 0xff;
const char HAL_UART1_CTS_PIN = 0xff;
const char HAL_UART1_RTS_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_TXD_PIN = 0xff;
const char HAL_UART2_RXD_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char HAL_UART3_DTE_RI_EINT = 0xff;
const char HAL_UART3_DTE_DCD_EINT = 0xff;
const char HAL_UART3_DTE_DSR_EINT = 0xff;
const char HAL_UART3_DTE_DCD_PIN = 0xff;
const char HAL_UART3_DTE_DSR_PIN = 0xff;
const char HAL_UART3_DTE_DTR_PIN = 0xff;
const char HAL_UART3_DTE_RI_PIN = 0xff;
const char HAL_SPI_MASTER_0_CS_PIN = 0xff;
const char HAL_SPI_MASTER_0_SCK_PIN = 0xff;
const char HAL_SPI_MASTER_0_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER_0_MISO_PIN = 0xff;
const char HAL_SPI_MASTER_1_CS_PIN = 0xff;
const char HAL_SPI_MASTER_1_SCK_PIN = 0xff;
const char HAL_SPI_MASTER_1_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER_1_MISO_PIN = 0xff;
const char HAL_SPI_MASTER_2_CS_PIN = 0xff;
const char HAL_SPI_MASTER_2_SCK_PIN = 0xff;
const char HAL_SPI_MASTER_2_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER_2_MISO_PIN = 0xff;
const char HAL_SPI_SLAVE_0_CS_PIN = 0xff;
const char HAL_SPI_SLAVE_0_SCK_PIN = 0xff;
const char HAL_SPI_SLAVE_0_MOSI_PIN = 0xff;
const char HAL_SPI_SLAVE_0_MISO_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;





