/* Copyright Statement:
 *
 * (C) 2005-2016  MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
 * Without the prior written permission of MediaTek and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
 * if you have agreed to and been bound by the applicable license agreement with
 * MediaTek ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of MediaTek Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */


#ifndef CUSTOM_RESOURCE_DEF_H
#define CUSTOM_RESOURCE_DEF_H




/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMAGE_ID_ANCS_NOTIFY_BMP = 3 + 1, /* BASE_ID + 1 */
    IMAGE_ID_ANDROID_NOTIFY_BMP,
    IMAGE_ID_BATT_CHARGING_BMP,
    IMAGE_ID_BATT_POWER_FULL_BMP,
    IMAGE_ID_BATT_POWER_HIGH_BMP,
    IMAGE_ID_BATT_POWER_LOW_BMP,
    IMAGE_ID_BATT_POWER_MIDDLE_BMP,
    IMAGE_ID_BT_CALL_CLOSE_BMP,
    IMAGE_ID_BT_CALL_HANG_UP_BMP,
    IMAGE_ID_BT_CALL_INCOMING_BMP,
    IMAGE_ID_BT_CALL_MISSED_BMP,
    IMAGE_ID_BT_CALL_OUTGOING_BMP,
    IMAGE_ID_BT_DISCONNECT_BMP,
    IMAGE_ID_BT_STATUS_DISCONNECT_BMP,
    IMAGE_ID_BT_STATUS_MULTI_LINK_BMP,
    IMAGE_ID_BT_STATUS_SINGLE_LINK_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_0_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_1_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_2_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_3_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_4_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_5_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_6_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_7_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_8_BMP,
    IMAGE_ID_DATE_CLOCK_DIGIT_9_BMP,
    IMAGE_ID_DATE_DOT_BMP,
    IMAGE_ID_DIGITAL_CLOCK_COLON_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_0_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_1_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_2_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_3_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_4_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_5_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_6_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_7_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_8_BMP,
    IMAGE_ID_DIGITAL_CLOCK_DIGIT_9_BMP,
    IMAGE_ID_FMP_SERVER_BMP,
    IMAGE_ID_MAINMENU_BT_SCAN_BMP,
    IMAGE_ID_MAINMENU_FMP_CLIENT_BMP,
    IMAGE_ID_MUSIC_STATUS_PLAYING_BMP,
    IMAGE_ID_SAMPLE_BMP,
    CUSTOM_RESOURCE_IMG_MAX
}custom_resource_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* CUSTOM_RESOURCE_DEF_H */
