/*
 * Generated by MTK Easy PinMux Tool Version 1.0.5 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Wed Jun 22 17:20:19 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char BSP_GPS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char HAL_MSDC_EINT = 19;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;




