/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-13 09:55:10:0571
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_GNSS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char SENSOR_EINT = 14;
const unsigned char SENSOR_EINT_G = 15;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;



